title: Wisk Yu-Gi-Oh!
description: Wisk Yu-Gi-Oh! Blog, articles and more
image: /assets/images/og-image.jpg
url: "https://wisk-yugioh.github.io"
lang: sl

author: Alen Bizjak

markdown: kramdown
future: true

collections:
  clanki:
    output: true
    permalink: /clanki/:year/:month/:day/:title
  reportaze:
    output: true
    permalink: /reportaze/:year/:month/:day/:title
  articles:
    output: true
    permalink: /articles/:year/:month/:day/:title
  reports:
    output: true
    permalink: /reports/:year/:month/:day/:title
  objave:
    output: true
    permalink: /objave/:year/:month/:day/:title
  announcements:
    output: true
    permalink: /announcements/:year/:month/:day/:title

defaults:
  - scope:
      type: clanki
    values:
      layout: post
      lang: sl
  - scope:
      type: reportaze
    values:
      layout: post
      lang: sl
  - scope:
      type: articles
    values:
      layout: post
      lang: en
  - scope:
      type: reports
    values:
      layout: post
      lang: en
  - scope:
      type: objave
    values:
      layout: post
      lang: sl
  - scope:
      type: announcements
    values:
      layout: post
      lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - not_published
  - _converted
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - PLAN.md
  - CHANGELOG.md
  - TODOS.md
  - COPILOT.md
