title: Wisk Yu-Gi-Oh!
description: Wisk Yu-Gi-Oh! Blog, articles and more
image: /assets/images/og-image.jpg
url: "https://wisk-yugioh.github.io"
baseurl: ""
lang: sl

author: Alen Bizjak

markdown: kramdown
future: true

collections:
  clanki:
    output: true
    permalink: /clanki/:year/:month/:day/:title
  reportaze:
    output: true
    permalink: /reportaze/:year/:month/:day/:title
  articles:
    output: true
    permalink: /articles/:year/:month/:day/:title
  reports:
    output: true
    permalink: /reports/:year/:month/:day/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - not_published
  - _converted
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - PLAN.md
  - CHANGELOG.md
  - TODOS.md
  - COPILOT.md
