title: Wisk Yu-Gi-Oh!
description: Wisk Yu-Gi-Oh! Blog, articles and more
url: "https://wisk-yugioh.github.io"
baseurl: ""
lang: sl

author: Alen Bizjak

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: true

collections:
  historic:
    output: true
    permalink: /historic/:year/:month/:day/:title
  sezona:
    output: true
    permalink: /sezona/:year/:month/:day/:title
  blog_en:
    output: true
    permalink: /blog-en/:year/:month/:day/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - not_published
  - Gemfile
  - Gemfile.lock
  - README.md
  - PLAN.md
  - CHANGELOG.md
  - TODOS.md
  - COPILOT.md
