#!/usr/bin/env node
// fetch-youtube.js — fetches the latest video across configured YouTube channels
// and writes the result to _data/latest_video.yml.
// Reads channel list from _data/youtube_channels.yml (no API key required).
// Run by the GitHub Actions workflow on a schedule, or manually.

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { DOMParser } from "xmldom";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dir, "..");

// ── helpers ──────────────────────────────────────────────────────────────────

function rssUrl(channelId) {
  return `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
}

async function fetchRss(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

function text(parent, tag) {
  return parent.getElementsByTagName(tag)?.[0]?.textContent ?? "";
}

function extractVideo(xml) {
  const doc   = new DOMParser().parseFromString(xml, "text/xml");
  const entry = doc.getElementsByTagName("entry")?.[0];
  if (!entry) return null;

  const videoId     = text(entry, "yt:videoId");
  const title       = text(entry, "title");
  const published   = text(entry, "published");
  const channelName = text(doc.getElementsByTagName("author")?.[0], "name");

  return { videoId, title, published, channelName };
}

// ── main ─────────────────────────────────────────────────────────────────────

const channelsYml = readFileSync(resolve(root, "_data/youtube_channels.yml"), "utf8");
// Lightweight YAML parse for the simple list-of-objects format used in the file.
const channels = channelsYml
  .split(/\n(?=-)/)
  .map(block => {
    const handle     = (block.match(/handle:\s*(.+)/) || [])[1]?.trim();
    const channel_id = (block.match(/channel_id:\s*(.+)/) || [])[1]?.trim();
    return handle && channel_id ? { handle, channel_id } : null;
  })
  .filter(Boolean);

if (channels.length === 0) {
  console.error("No channels found in _data/youtube_channels.yml");
  process.exit(1);
}

const results = await Promise.allSettled(
  channels.map(async ch => {
    const xml   = await fetchRss(rssUrl(ch.channel_id));
    const video = extractVideo(xml);
    if (!video || !video.videoId) throw new Error(`No entries for channel ${ch.handle}`);
    return video;
  })
);

const videos = results
  .filter(r => r.status === "fulfilled")
  .map(r => r.value);

results
  .filter(r => r.status === "rejected")
  .forEach(r => console.warn("Warning:", r.reason?.message));

if (videos.length === 0) {
  console.error("Could not fetch any videos. Keeping existing _data/latest_video.yml.");
  process.exit(0);
}

const latest = videos.reduce((a, b) =>
  new Date(a.published) >= new Date(b.published) ? a : b
);

const yml = [
  `# Auto-generated by scripts/fetch-youtube.js — do not edit manually.`,
  `video_id: "${latest.videoId}"`,
  `title: "${latest.title.replace(/"/g, '\\"')}"`,
  `channel: "${latest.channelName.replace(/"/g, '\\"')}"`,
  `published: "${latest.published}"`,
  `thumbnail: "https://img.youtube.com/vi/${latest.videoId}/hqdefault.jpg"`,
  `url: "https://www.youtube.com/watch?v=${latest.videoId}"`,
].join("\n") + "\n";

const outPath = resolve(root, "_data/latest_video.yml");
writeFileSync(outPath, yml);
console.log(`Written latest_video.yml — "${latest.title}" (${latest.channelName})`);
